"""empty message

Revision ID: 341205842be2
Revises: 
Create Date: 2025-04-18 13:58:25.681636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341205842be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=300), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cnpj'), ['cnpj'], unique=True)

    op.create_table('motoristas',
    sa.Column('Id_motorista', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_motorista', sa.String(length=255), nullable=False),
    sa.Column('CPF', sa.String(length=11), nullable=False),
    sa.Column('CNH', sa.String(length=20), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.Column('Telefone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id_motorista')
    )
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motoristas_CNH'), ['CNH'], unique=True)
        batch_op.create_index(batch_op.f('ix_motoristas_CPF'), ['CPF'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veiculos',
    sa.Column('ID_VEICULO', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PLACA', sa.String(length=7), nullable=False),
    sa.Column('MARCA', sa.String(length=50), nullable=False),
    sa.Column('MODELO', sa.String(length=50), nullable=False),
    sa.Column('COR', sa.String(length=20), nullable=False),
    sa.Column('ANO_FABRICACAO', sa.Integer(), nullable=False),
    sa.Column('RENAVAM', sa.String(length=11), nullable=False),
    sa.Column('CHASSI', sa.String(length=20), nullable=False),
    sa.Column('TIPO_CARROCERIA', sa.String(length=50), nullable=False),
    sa.Column('CAPACIDADE_CARGA', sa.Float(), nullable=False),
    sa.Column('STATUS', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID_VEICULO')
    )
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculos_CHASSI'), ['CHASSI'], unique=True)
        batch_op.create_index(batch_op.f('ix_veiculos_PLACA'), ['PLACA'], unique=True)
        batch_op.create_index(batch_op.f('ix_veiculos_RENAVAM'), ['RENAVAM'], unique=True)

    op.create_table('entregas',
    sa.Column('id_entrega', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj_cliente', sa.String(length=14), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=False),
    sa.Column('logradouro_entrega', sa.String(length=300), nullable=False),
    sa.Column('bairro_entrega', sa.String(length=50), nullable=False),
    sa.Column('cidade_entrega', sa.String(length=50), nullable=False),
    sa.Column('estado_entrega', sa.String(length=2), nullable=False),
    sa.Column('cep_entrega', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('data_entrega', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cnpj_cliente'], ['clientes.cnpj'], ),
    sa.PrimaryKeyConstraint('id_entrega'),
    sa.UniqueConstraint('nota_fiscal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregas')
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_RENAVAM'))
        batch_op.drop_index(batch_op.f('ix_veiculos_PLACA'))
        batch_op.drop_index(batch_op.f('ix_veiculos_CHASSI'))

    op.drop_table('veiculos')
    op.drop_table('user')
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motoristas_CPF'))
        batch_op.drop_index(batch_op.f('ix_motoristas_CNH'))

    op.drop_table('motoristas')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_cnpj'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
