"""empty message

Revision ID: 4e0512247246
Revises: 
Create Date: 2025-04-03 12:19:17.472002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0512247246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=300), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cnpj'), ['cnpj'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_cnpj'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
