"""empty message

Revision ID: cf06f1fd87e9
Revises: ce7fdc516a30
Create Date: 2025-04-17 16:09:19.872810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf06f1fd87e9'
down_revision = 'ce7fdc516a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
